DROP TABLE CLIENTE;
DROP TABLE CONTATO;
DROP SEQUENCE S_ID_CONTATO;
DROP SEQUENCE S_ID_CLIENTE;

CREATE TABLE CONTATO
(
ID_CONTATO NUMBER NOT NULL,
EMAIL VARCHAR2(200) NOT NULL,
TELEFONE VARCHAR2 (50) NOT NULL,

CONSTRAINT CONTATO_PK PRIMARY KEY (ID_CONTATO) ENABLE

);

CREATE TABLE CLIENTE
(
ID_CLIENTE NUMBER NOT NULL,
NOME VARCHAR2(200) NOT NULL,
CPF VARCHAR2(22) NOT NULL,
SEXO VARCHAR2(10) NOT NULL,
INTERESSES VARCHAR2(4000) NOT NULL,
IDADE NUMBER NOT NULL,
LISTACONTATO NUMBER NULL,

CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE) ENABLE,
CONSTRAINT LISTACONTATO_FK FOREIGN KEY (LISTACONTATO) REFERENCES CONTATO (ID_CONTATO)
);

CREATE SEQUENCE S_ID_CONTATO INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE S_ID_CLIENTE INCREMENT BY 1 START WITH 1 MINVALUE 1;